### ISSUE TITLE
Multiple lists - SPServices webURL

### ISSUE THREAD

**Issue by marcinsadlo** [michaelsoriano/sp-bootstrap-list-viewer#1]
Hello!

I checked your sp-bootstrap-list-viewer, it's a nice modern combination of SPServices with bootstrap. I am often using SPServices to grab list items from several lists in Site Collection. 

Can you suggest how to combine multiple lists from  different sites / sub-sites in this one view? 
What I am missing from my current SPServices implementations - where to specify "webURL" / or several webURL's for the lists in your script? 

I am often using an array for that - like:

var urls = [
{
    name : "http://...subsite1"
  }, 
 {
    name : "http://...subsite2"
  }, 
...

for (var i = 0; i < urls.length; i++) {
$().SPServices({
operation: "GetListItems",
webURL: urls[i].name,
...

and it works quite good - for example with listing menu items.

Thank you in advance for any suggestions!

Best regards,
Marcin

**Comment by michaelsoriano** [comment]
I see what you're saying where you call spservices multiple times - depending on the number of lists, then you just keep appending into an array of items. 

But this plugin though doesn't grab all of the list items in 1 call. It only grabs only the number of items in the "rowLimit" parameter. Then it grabs the next chunk in the paginated results. 

The reason I did that is to reduce the payload size - to only what the user needs to see. For example, if you have a list of a million records - I'm not grabbing all million rows then just show the first 10. Instead, I ONLY grab the 10 records and keep fetching as the user paginates. 

So doing multiple lists means you will have to fetch all records and combine - then build your own paging system.
